### ISSUE TITLE
Help with duplicating bank statement line

### ISSUE THREAD

**Issue by archont00** [kedder/ofxstatement-sample#1]
Hi,

this is not an "issue" with ofxstatement-sample, but a kind request for help with coding.

The CSV file may contain not only the amount in the single line, but also some of the fee types. E.g.:

```
date      ,memo   ,amount,fee1 ,fee2 ,fee3
03.12.2016,Blabla1,-10.00,     ,     ,    
04.12.2016,Blabla2,-10.00,-4.00,     ,    
05.12.2016,Blabla3,      ,     ,-4.00,    
```

The fees should not be added to `amount` (if `amount <> 0`), but a new line should be generated instead. Also, trn_type might be defined to distinguish the fee from the underlying transaction. E.g.:

```
date      ,memo   ,trn_type,amount
03.12.2016,Blabla1,        ,-10.00
04.12.2016,Blabla2,        ,-10.00
04.12.2016,Blabla2,FEE     , -4.00
05.12.2016,Blabla3,FEE     , -4.00
```

I am a newbie in python - good enough to modify the existing CSV plugins to make them work with my bank's CSV export, but nothing more.

At the moment, I pre-process the csv file with a bash script (to duplicate the lines as shown above), but this extra step blocks me from publishing the ofxstatement plugin.

Any help appreciated.

**Comment by archont00** [comment]
Solved via contribution of other developer

https://github.com/archont00/ofxstatement-airbankcz/pull/2

**Comment by kedder** [comment]
Ugh, sorry for not responding, @archont00, I completely missed this issue. 

Creating several StatementLines out of single csv line is pretty simple if you override `parse` method directly instead of `parse_record` and just implement your own loop over the csv lines. The you're free to create as many transactions for each line as you want.

I'm glad it was resolved though.
